# Generated by Django 5.2 on 2025-06-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
    ]
