# Generated by Django 5.2 on 2025-06-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
