# Generated by Django 5.2 on 2025-06-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_coupon_shippingzone_tag_alter_size_options_and_more'),
        ('store', '0017_alter_productimage_color'),
    ]

    operations = [
    ]
